### PR TITLE
Update API permissions, fix community settings page

### LINKED ISSUE #221: Add moderator for community - error occur
Screen Shot 2021-02-25 at 9 48 13 AM

I was trying to add Michael to the moderators of OutbreakSci community, but encountered an error.

### PR DESCRIPTION
**Pull request by jheretic**
This PR significantly tightens up API permissions, and further limits the possibility of information leakage. To test, it should be verified that the the permissions have not been tightened too far, so that:
* A logged-in user can still submit a rapid review, full review, and comment
* A user can change their settings
* An admin or a non-admin designated community owner can edit the settings on a community

Additionally, this branch contains a number of fixes for the community settings page. To test:
* Verify that an admin or a non-admin community owner can both add and delete community members, owners, events, and tags (frontend state fixes pending a future update)
* Verify that the community description and image can be updated.

Fixes #221 #222 #225

### CODE REVIEW

**Review by harumhelmy — CHANGES_REQUESTED** [review]
Hi hi! Thanks for this @jheretic. A single community page would crash for me whenever there's no user logged in & when I was logged in as a site-wide admin, the icon for the /community-settings/ page wouldn't show. I pushed up some quick frontend fixes for that. I'm still unable to add a moderator to the community, however, did that ever work for you?

**Comment by jheretic** [comment]
Thanks @harumhelmy! Hmm, adding moderators did work for me previously. I'll re-test to see if I can figure out what the issue is. Were you trying to add them as an admin, or as community moderator/owner (both should work, just curious for debugging purposes)?

**Comment by harumhelmy** [comment]
@jheretic The latter, I believe: [Screen Shot 2021-03-08 at 17 47 25](https://user-images.githubusercontent.com/13320420/110392067-62da6000-8036-11eb-9510-3e1b5d94d7c9.png)

**Comment by jheretic** [comment]
I believe this is resolved now. Merging!

**Pull request merged**
