### PR TITLE
Build out new homepage

### PR DESCRIPTION
**Pull request by rudietuesdays**
This PR is the build for the new PREreview.org homepage. It includes designs from the [figma](https://www.figma.com/file/wo6SjH2DBuXf4DgL8rDBOX/PREreview?node-id=1713%3A1082) template.

This PR is a work in progress, and the following items are needed for completion, from top to bottom of the page:

- [x] A finalized header menu
- [ ] Links for the resource cards (the strata under the search bar)
- [x] Missing screenshot image for the "explore communities" item
- [ ] Links for all the buttons in the grid that starts with "inviting everyone to the table"
- [ ] Quotes about PREreview to go in the carousel
- [ ] Missing images and alt captions for the "Press and Awards" strata
- [ ] A finalized design for the "Stay Connected" strata
- [ ] A finalized footer

### CODE REVIEW

**Comment by murkatr** [comment]
Thank you, @rudietuesdays. 
I will take on the following: 
- [ ] Finalize quote consent with mentees 
- [ ] Gather Press and Awards images and alt captions
- [ ] Finalize the “Stay Connected” design using MailChimp’s HTML

**Comment by dasaderi** [comment]
@murkatr, we are exploring using CRM for the newsletter, so please hold off on Mailchimp. 

@rudietuesdays I'm on the rest of the checklist now.

**Comment by dasaderi** [comment]
Screenshot image uploaded https://github.com/PREreview/prereview-project-assets/tree/master/screenshots.

**Comment by georgiamoon** [comment]
@dasaderi I finally did a pass on the footer — take a look and feel free to edit. Very modeled on sfdora.org.

**Pull request merged**
