### PR TITLE
Review workflow overhaul

### LINKED ISSUE #122: Update submit reviews workflow based on new wireframes
Wireframes here: https://github.com/PREreview/prereview/issues/121

### LINKED ISSUE #136: Conflict of Interest Error
If the Conflict of Interest box is not checked after a rapid review is filled out then it doesn't get addressed if the user chooses to work on a long-form review.

No COI dialog box

### PR DESCRIPTION
**Pull request by rudietuesdays**
This PR is a full overhaul of the review workflow to reflect latest changes to the wireframes: https://www.figma.com/file/wo6SjH2DBuXf4DgL8rDBOX/PREreview?node-id=521%3A313

If fully working, all options will take a user successfully through the review process, whether or not they chose to fill out a longform review.

* Fixes #122 
* Fixes #136

### CODE REVIEW

**Review by harumhelmy — COMMENTED** [review]
This is looking so freaking good @rudietuesdays ! All the expected functionalities are working great for me so far -- you know of anything I should specifically try to reproduce bugs?

**Comment by harumhelmy** [comment]
On a second check, it turns out I was able to submit a second review, so I'm working on refactoring the checks in place for whether a user has reviewed and/or requested.

**Comment by harumhelmy** [comment]
Hi @rudietuesdays I pushed up some refactoring of the useEffect hook that checks for the user's latest draft & whether the user has long reviewed -- now a user shouldn't be able to submit multiple long reviews & should only get drafts that they themself wrote. Would you mind testing this or giving another look?

**Comment by rudietuesdays** [comment]
Thank you for this review @harumhelmy ! It looked great, but I was experiencing a bug where on submit of a rapid review, it would successfully submit in the back end but on the front end the stepper wouldn't move forward. That should be fixed now if you can take another look!

**Review by harumhelmy — CHANGES_REQUESTED** [review]
Okay so I just started seeing that bug (wherein a rapid review is submitted in the backend but the frontend stepper isn't moving forward, and you end up submitting multiple reviews) too @rudietuesdays! It's still happening on my end on both Chrome and Firefox, and I realized that it only happens when a user is newly logged in and hasn't refreshed the browser, for some reason it doesn't happen when I am newly logged in and then refresh the browser, if that is a clue.

**Comment by rudietuesdays** [comment]
> Okay so I just started seeing that bug (wherein a rapid review is submitted in the backend but the frontend stepper isn't moving forward, and you end up submitting multiple reviews) too @rudietuesdays! It's still happening on my end on both Chrome and Firefox, and I realized that it only happens when a user is newly logged in and hasn't refreshed the browser, for some reason it doesn't happen when I am newly logged in and then refresh the browser, if that is a clue.

@harumhelmy I wonder if this would be fixed by the user context updates I added to develop? I'd love to try to merge this if it's ok otherwise, and create a new issue for the bug if it persists!

**Pull request merged**
