### PR TITLE
fix fallback for missing pdf and style data displayed instead

### LINKED ISSUE #119: Loading PDF... spins forever
Occuring on individual preprint pages. Check if this is an issue with the site or the info coming in externally and troubleshoot as needed.

### PR DESCRIPTION
**Pull request by rudietuesdays**
This PR renders info about a preprint if there is no content to display from the pdf url. 

Fixes #119 

Good test DOIs are 10.1101/833392 and 10.3128/550

### CODE REVIEW

**Comment by jheretic** [comment]
@rudietuesdays About those test preprints, 10.1101/833392 showed up with a PDF and I couldn't resolve 10.3128/550 at all. Were those from imported data, or via the `Add Review|Request Review` button? Not sure how to test if the latter.

**Comment by rudietuesdays** [comment]
Thanks for checking @jheretic ! I didn't think of it before but 10.3128/550 was made from dummy data, so it makes sense that that didn't resolve. 

Interesting and curious that the other one resolved with a PDF; not sure why it isn't for me. I'm receiving a 403 when the object tries to fetch the URL, so instead it displays as below:
Screen Shot 2021-01-20 at 3 34 33 PM

I grabbed this one from https://www.prereview.org/preprints/doi/10.1101/833392/ as a link that didn't have a PDF attached, but if there's another one from prereview.org that is resolving without a PDF for you I think that'd be a good way to test?

**Comment by jheretic** [comment]
@rudietuesdays Doing some testing (I ended up temporarily editing the resolver so it doesn't populate the PDF urls) and I'm a little confused about the logic flow. Does the `<object>` automatically fallback to the containing text if `pdfUrl` is undefined? Because it looks to me like it can only hit that branch in the ternary if `pdfUrl` IS defined, so it never fails over. But I'm not sure if I'm understanding that correctly; is there some other way you're checking for a lack of presence of a PDF than checking to see if `pdfUrl` is empty?

**Comment by rudietuesdays** [comment]
> @rudietuesdays Doing some testing (I ended up temporarily editing the resolver so it doesn't populate the PDF urls) and I'm a little confused about the logic flow. Does the `<object>` automatically fallback to the containing text if `pdfUrl` is undefined? Because it looks to me like it can only hit that branch in the ternary if `pdfUrl` IS defined, so it never fails over. But I'm not sure if I'm understanding that correctly; is there some other way you're checking for a lack of presence of a PDF than checking to see if `pdfUrl` is empty?

@jheretic So yes, pdfUrl should always be defined! That check was a holdover from the previous version of the platform, and I just added a commit removing it. The rest of the content inside the `object` is the fallback for in case the pdfUrl doesn't render for some reason (a 400 error or whatever). So that should all render only if a PDF is not found at the url.

**Comment by jheretic** [comment]
With the latest fixes, this works fine for me now!

**Pull request merged**
